---@class UnityEngine.SystemInfo : object
---@field public batteryLevel float
---@field public batteryStatus UnityEngine.BatteryStatus
---@field public operatingSystem string
---@field public operatingSystemFamily UnityEngine.OperatingSystemFamily
---@field public processorType string
---@field public processorFrequency int
---@field public processorCount int
---@field public systemMemorySize int
---@field public graphicsMemorySize int
---@field public graphicsDeviceName string
---@field public graphicsDeviceVendor string
---@field public graphicsDeviceID int
---@field public graphicsDeviceVendorID int
---@field public graphicsDeviceType UnityEngine.Rendering.GraphicsDeviceType
---@field public graphicsUVStartsAtTop bool
---@field public graphicsDeviceVersion string
---@field public graphicsShaderLevel int
---@field public graphicsMultiThreaded bool
---@field public supportsShadows bool
---@field public supportsRawShadowDepthSampling bool
---@field public supportsMotionVectors bool
---@field public supportsRenderToCubemap bool
---@field public supportsImageEffects bool
---@field public supports3DTextures bool
---@field public supports2DArrayTextures bool
---@field public supports3DRenderTextures bool
---@field public supportsCubemapArrayTextures bool
---@field public copyTextureSupport UnityEngine.Rendering.CopyTextureSupport
---@field public supportsComputeShaders bool
---@field public supportsInstancing bool
---@field public supportsSparseTextures bool
---@field public supportedRenderTargetCount int
---@field public usesReversedZBuffer bool
---@field public npotSupport UnityEngine.NPOTSupport
---@field public deviceUniqueIdentifier string
---@field public deviceName string
---@field public deviceModel string
---@field public supportsAccelerometer bool
---@field public supportsGyroscope bool
---@field public supportsLocationService bool
---@field public supportsVibration bool
---@field public supportsAudio bool
---@field public deviceType UnityEngine.DeviceType
---@field public maxTextureSize int
---@field public maxCubemapSize int
---@field public unsupportedIdentifier string
local m = {}
---@param format UnityEngine.RenderTextureFormat
---@return bool
function m.SupportsRenderTextureFormat(format) end
---@param format UnityEngine.TextureFormat
---@return bool
function m.SupportsTextureFormat(format) end
return m