---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/28 14:15
---

local yk = require("Core.YK")
local sceneBase = require("Core.SceneBaseLua")
local windname = require("Game.Def.WindNames")
local threeEliminateWind = require("Game.ThreeEliminate.ThreeEliminateWind")
---@class ThreeEliminateScene : SceneBaseLua
local this = yk.Scene_class(sceneBase)
function this:ctor()

end
function this:OnInit(param)
    self:AddLoadGrop("ThreeEliminate")
end

function this:OnEnter()
    yk.YKSupportLua.ShowWindow(windname.ThreeEliminateWind,nil,threeEliminateWind,true )
    --yk.YKSupportLua.ShowWindow(windname.ThreeEliminateWind,nil,ThreeEliminateWind)
    yk.LoadingUI.Instance:Destroy()
end
return this
