---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/25 19:37
---
local fgui = require("FGUI.FairyGUI")
---@class test : FairyGUI.GComponent
local this = fgui.extension_class(nil,fgui.GLuaComponent)

function this:ctor()
    self.n1 = self:GetChild("n1") ---@type FairyGUI.TextField
end

function this:test(text)
    self.n1.text = text
end
return this