---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/23 20:17
---
local windowsBase = require("Core.WindowBase")
local fgui = require("FGUI.FairyGUI")
local yk = require("Core.YK")
---@class TestWind :WindowBase
local this= yk.wind_class(windowsBase)
function this:ctor(ins)

    self.resName = "LoginWindow"
    self.packName = "LoadingScenePack"
    self.isNeedHideAnimation = false
    self.isNeedShowAnimation = false
    print(self.resName)
    ---@type FairyGUI.GComponent
    local url = fgui.UIPackage.GetItemURL(self.packName,"TestLogin")
    fgui.register_extension(url,require("Game.ext.Test"))
end

function this:OnInit()
    --local test = self.Objs.TestLogin ---@type test
    --test:test()
end

function this:OnShown(param)

end

function this:OnBtnClick(btn)
    print(btn.sender.name)
end

return this