// Generated by sprotodump. DO NOT EDIT!
// source: F:\sprotodump-master\a\package.sproto

using System;
using Sproto;
using System.Collections.Generic;

namespace SprotoType { 
	public class package : SprotoTypeBase {
		private static int max_field_count = 3;
		
		
		private Int64 _protoId; // tag 0
		public Int64 protoId {
			get { return _protoId; }
			set { base.has_field.set_field (0, true); _protoId = value; }
		}
		public bool HasProtoId {
			get { return base.has_field.has_field (0); }
		}

		private Int64 _session; // tag 1
		public Int64 session {
			get { return _session; }
			set { base.has_field.set_field (1, true); _session = value; }
		}
		public bool HasSession {
			get { return base.has_field.has_field (1); }
		}

		private Int64 _errorcode; // tag 2
		public Int64 errorcode {
			get { return _errorcode; }
			set { base.has_field.set_field (2, true); _errorcode = value; }
		}
		public bool HasErrorcode {
			get { return base.has_field.has_field (2); }
		}

		public package () : base(max_field_count) {}

		public package (byte[] buffer) : base(max_field_count, buffer) {
			this.decode ();
		}

		protected override void decode () {
			int tag = -1;
			while (-1 != (tag = base.deserialize.read_tag ())) {
				switch (tag) {
				case 0:
					this.protoId = base.deserialize.read_integer ();
					break;
				case 1:
					this.session = base.deserialize.read_integer ();
					break;
				case 2:
					this.errorcode = base.deserialize.read_integer ();
					break;
				default:
					base.deserialize.read_unknow_data ();
					break;
				}
			}
		}

		public override int encode (SprotoStream stream) {
			base.serialize.open (stream);

			if (base.has_field.has_field (0)) {
				base.serialize.write_integer (this.protoId, 0);
			}

			if (base.has_field.has_field (1)) {
				base.serialize.write_integer (this.session, 1);
			}

			if (base.has_field.has_field (2)) {
				base.serialize.write_integer (this.errorcode, 2);
			}

			return base.serialize.close ();
		}
	}


}

