---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/27 0:28
---
local YK = require("Core.YK")
---@class LuaModeBase : YKSupportLua.LuaMode
local m = {}
function m:ctor()
    self.IsLoginDataOk = false
end
function m:OnClear() end
function m:OnDestroy() end
function m:OnInitData()
    self.IsLoginDataOk = false
end
function m:OnLogin()
    self.IsLoginDataOk = true
end
return m