---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/15 17:15
---

local YK = require("Core.YK")
---@class SceneBaseLua : YKSupportLua.LuaSceneBase
local this = YK.Scene_class()
--[[
    默认的构造函数
]]--
---@param ins YKSupportLua.LuaSceneBase
function this:ctor(ins)
    self.csuserdata = ins

    --print("--------------------------")
end

--[[
    进入场景调用的
]]
function this:OnEnter()

end

--[[
    离开场景调用的函数
]]
function this:OnLeave()
end

--[[
	加载完成
]]
function this:OnResLoaded()

end

--[[
	加载失败
]]
function this:OnTaskFailure(taskName, error)
end

--[[
	初始化这个场景的时候调用的函数
]]
function this:OnInit( param )
end

---@param evdata EventData
function this:OnHandler(evdata)
    
end
return this