//解压后把整个CS文件夹拖入Unity工程即可。当我在拖入Unity的时候发现Settings.cs报错了，查了一下是因为mono并不是完整的.net 。不过这个文件我们不需要用，所以直接把Settings.cs删除即可。

////------------------------------------------------------------------------------
//// <autogenerated>
////     This code was generated by a tool.
////     Runtime Version:2.0.40607.42
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </autogenerated>
////------------------------------------------------------------------------------

//namespace LzmaAlone.Properties
//{
//    public partial class Settings : System.Configuration.ApplicationSettingsBase
//    {
//        private static Settings m_Value;

//        private static object m_SyncObject = new object();

//        public static Settings Value
//        {
//            get
//            {
//                if ((Settings.m_Value == null))
//                {
//                    System.Threading.Monitor.Enter(Settings.m_SyncObject);
//                    if ((Settings.m_Value == null))
//                    {
//                        try
//                        {
//                            Settings.m_Value = new Settings();
//                        }
//                        finally
//                        {
//                            System.Threading.Monitor.Exit(Settings.m_SyncObject);
//                        }
//                    }
//                }
//                return Settings.m_Value;
//            }
//        }
//    }
//}
