---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/28 15:37
---

local this = {}
this.ThreeEliminateWind = "ThreeEliminateWind"
this.SelectLevelWind = "SelectLevelWind"
return this