---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/20 20:09
---
local YK = require("Core.YK")
local sceneBase = require("Core.SceneBaseLua")
local luaTestWind = require("Game.Windows.testwinddd")
---@class TestLua : SceneBaseLua
local TestLua = YK.Scene_class(sceneBase)
local this = TestLua

function this:ctor(ins)
    --self.super:ctor(ins)
    print("ctor")
end
--[[
    进入场景调用的
]]
function this:OnEnter()
    print("进入测试场景"..self.SceneName)
    YK.YKSupportLua.ShowWindow("test",nil,luaTestWind)

end

--[[
    离开场景调用的函数
]]
function this:OnLeave()
end

--[[
	加载完成
]]
function this:OnResLoaded()

end

--[[
	加载失败
]]
function this:OnTaskFailure(taskName, error)
end

--[[
	初始化这个场景的时候调用的函数
]]
function this:OnInit( param )
    self:AddLoadGrop("test")
    --self.AddLoadGrop(self.csuserdata,"test")
end

---@param evdata EventData
function this:OnHandler(evdata)

end

return this;
