---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2018/6/14 21:41
---

require("Core.class")

function pTable(Lua_table)

    -- do

    --     return

    -- end



    local function define_print(_tab,str)

        str = str .. "  "

        for k,v in pairs(_tab) do

            if type(v) == "table" then

                if not tonumber(k) then

                    print(str.. k .."{")

                else

                    print(str .."{")

                end

                define_print(v,str)

                print( str.."}")

            else

                print(str .. tostring(k) .. " " .. tostring(v))

            end

        end

    end

    if type(Lua_table) == "table" then

        define_print(Lua_table," ")

    else

        print(tostring(Lua_table))

    end

end

local ThreeEliminateScene = require("Game.ThreeEliminate.ThreeEliminateScene")
local fgui = require("FGUI.FairyGUI")
local YK = require("Core.YK")

local Main = {}
function Main.Main()
    print("开始")
    fgui.Init()
    YK.Init()
    --fgui.GRoot.inst:SetContentScaleFactor(1242, 2208)
    YK.YKSupportLua.GotoScene("Test",nil,ThreeEliminateScene)
end

function Main.OnDestroy()
    
end

function Main.OnShowExit()
    
end


return Main